sudo: false
language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

matrix:
  fast_finish: true
  include:
    - env: TOXENV=splinter
      python: "3.7"
      addons:
        chrome: stable
    - env: TOXENV=qa
      python: "3.7"
    - env: TOXENV=type
      python: "3.7"

  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"


install: pip install tox-travis codecov

script: tox
after_success:
  - codecov -e TOXENV
